# Generated by Django 4.2.9 on 2024-02-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league_member',
            new_name='league_members',
        ),
    ]
