# Generated by Django 4.2.9 on 2024-02-20 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid name, it may only contain letters, numbers, spaces and - _ characters', regex='^[\\w\\s-]$')]),
        ),
    ]
